# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_temp',
            field=models.BooleanField(default=False, verbose_name='是否为临时工作流'),
        ),
    ]
