# Generated by Django 4.2.28 on 2026-02-13 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新对话', max_length=255, verbose_name='对话标题')),
                ('workspace', models.CharField(blank=True, default='', max_length=500, verbose_name='工作区路径')),
                ('model', models.CharField(default='glm-4-flash', max_length=50, verbose_name='使用的模型')),
                ('mode', models.CharField(default='chat', max_length=20, verbose_name='对话模式')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '对话会话',
                'verbose_name_plural': '对话会话',
                'db_table': 'ai_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统'), ('tool', '工具')], max_length=20, verbose_name='消息角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('tool_calls', models.JSONField(blank=True, null=True, verbose_name='工具调用信息')),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=100, verbose_name='工具调用ID')),
                ('tool_name', models.CharField(blank=True, default='', max_length=100, verbose_name='工具名称')),
                ('reasoning', models.TextField(blank=True, default='', verbose_name='思考过程')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation', verbose_name='所属对话')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'ai_message',
                'ordering': ['created_at'],
            },
        ),
    ]
