# Generated by Django 4.2.28 on 2026-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tool_calls',
            field=models.TextField(blank=True, default='', null=True, verbose_name='工具调用信息'),
        ),
    ]
