# Generated by Django 4.2.28 on 2026-03-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联工作流ID')),
                ('goal', models.TextField(verbose_name='任务目标')),
                ('workspace', models.CharField(blank=True, default='', max_length=1024, verbose_name='工作区')),
                ('phase', models.CharField(default='planning', max_length=32, verbose_name='当前阶段')),
                ('status', models.CharField(default='draft', max_length=32, verbose_name='会话状态')),
                ('master_plan', models.TextField(default='{}', verbose_name='主方案')),
                ('execution_pack', models.TextField(default='{}', verbose_name='执行包')),
                ('metadata', models.TextField(default='{}', verbose_name='扩展信息')),
                ('latest_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '协同会话',
                'verbose_name_plural': '协同会话',
                'db_table': 'ai_collaboration_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='ai', max_length=32, verbose_name='来源')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('content', models.TextField(default='{}', verbose_name='快照内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_snapshots', to='collaboration.collaborationsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '方案快照',
                'verbose_name_plural': '方案快照',
                'db_table': 'ai_collab_plan_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanNodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=128, verbose_name='节点ID')),
                ('node_title', models.CharField(blank=True, default='', max_length=256, verbose_name='节点标题')),
                ('detail_plan', models.TextField(default='{}', verbose_name='节点细化方案')),
                ('review_status', models.CharField(default='pending', max_length=32, verbose_name='审查状态')),
                ('human_comments', models.TextField(default='[]', verbose_name='人工审查备注')),
                ('reviewed_detail_plan', models.TextField(default='{}', verbose_name='人工修订后方案')),
                ('require_runtime_approval', models.BooleanField(default=False, verbose_name='运行时是否需要审批')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_reviews', to='collaboration.collaborationsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '节点审查记录',
                'verbose_name_plural': '节点审查记录',
                'db_table': 'ai_collab_plan_node_review',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('title', models.CharField(max_length=256, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务说明')),
                ('task_type', models.CharField(default='analysis', max_length=32, verbose_name='任务类型')),
                ('status', models.CharField(default='pending', max_length=32, verbose_name='任务状态')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级')),
                ('dependencies', models.TextField(default='[]', verbose_name='依赖任务')),
                ('constraints', models.TextField(default='[]', verbose_name='执行约束')),
                ('artifacts', models.TextField(default='{}', verbose_name='任务产出')),
                ('result_summary', models.TextField(blank=True, default='', verbose_name='结果摘要')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.PositiveIntegerField(default=1, verbose_name='最大重试次数')),
                ('requires_human_approval', models.BooleanField(default=False, verbose_name='是否需要人工审批')),
                ('is_high_risk', models.BooleanField(default=False, verbose_name='是否高风险')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='collaboration.collaborationsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '执行任务',
                'verbose_name_plural': '执行任务',
                'db_table': 'ai_collab_execution_task',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64, verbose_name='操作动作')),
                ('payload', models.TextField(default='{}', verbose_name='操作参数')),
                ('operator', models.CharField(default='human', max_length=64, verbose_name='操作者')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='collaboration.collaborationsession', verbose_name='会话')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='collaboration.executiontask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '人工介入记录',
                'verbose_name_plural': '人工介入记录',
                'db_table': 'ai_collab_execution_intervention',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='plannodereview',
            constraint=models.UniqueConstraint(fields=('session', 'node_id'), name='uniq_collab_session_node_review'),
        ),
        migrations.AddConstraint(
            model_name='executiontask',
            constraint=models.UniqueConstraint(fields=('session', 'task_id'), name='uniq_collab_session_task'),
        ),
    ]
