# Generated by Django 4.2.28 on 2026-03-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('question', 'AI提问'), ('answer', '用户回答'), ('system', '系统消息')], max_length=16, verbose_name='消息类型')),
                ('question_id', models.CharField(blank=True, default='', max_length=64, verbose_name='问题ID')),
                ('question_text', models.TextField(blank=True, default='', verbose_name='问题文本')),
                ('question_options', models.TextField(default='[]', verbose_name='问题选项(JSON数组)')),
                ('selected_option_ids', models.TextField(default='[]', verbose_name='选中的选项ID(JSON数组)')),
                ('selected_options', models.TextField(default='[]', verbose_name='选中的选项完整信息(JSON数组)')),
                ('custom_input', models.TextField(blank=True, default='', verbose_name='用户自定义输入')),
                ('ai_raw_request', models.TextField(blank=True, default='', verbose_name='AI原始请求')),
                ('ai_raw_response', models.TextField(blank=True, default='', verbose_name='AI原始响应')),
                ('index', models.IntegerField(default=0, verbose_name='消息索引')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration.collaborationsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '问答消息',
                'verbose_name_plural': '问答消息',
                'db_table': 'ai_chat_message',
                'ordering': ['session', 'index'],
            },
        ),
    ]